/*
Copyright 2025 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
// NOTE: json tags are required.  Any new fields you add must have json tags for the fields to be serialized.

// TelemetryConfigSpec defines the desired state of TelemetryConfig
type TelemetryConfigSpec struct {
	// INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
	// Important: Run "make" to regenerate code after modifying this file

	// Enabled defines if the telemetry agent should be enabled
	// +operator-sdk:csv:customresourcedefinitions:type=spec
	Enabled bool `json:"enabled,omitempty"`

	// The repository of the telemetry agent image to use.
	// +operator-sdk:csv:customresourcedefinitions:type=spec
	ImageRepository string `json:"imageRepository,omitempty"`

	// The version of the telemetry agent image to use.
	// +operator-sdk:csv:customresourcedefinitions:type=spec
	ImageVersion string `json:"imageVersion,omitempty"`

	// The path of the service account's credentials stored as a secret. This is the credential that
	// will be used to authenticate with the Google Cloud Telemetry Manager.
	// If not specified, it defaults to "/var/run/secrets/google/service_account.json".
	// In the case of Workload Identity Federation (WIF) / Workload Identity, this path points to the WIF config file.
	// For example: "/var/run/secrets/cloud.google.com/serviceaccount/file-name"
	// +operator-sdk:csv:customresourcedefinitions:type=spec
	ServiceAccountCredentialsPath string `json:"serviceAccountCredentialsPath,omitempty"`

	// The name of the Kubernetes secret containing the service account's credentials. This is the
	// credential that will be used to authenticate with the Google Cloud Telemetry Manager.
	// If not specified, it defaults to "google-cloud-cluster-services-telemetry-agent-wif-secret".
	// In the case of Workload Identity Federation (WIF) / Workload Identity, this secret is created
	// by applying the secret manifests generated by the ccoctl tool from the CredentialsRequest.
	// +operator-sdk:csv:customresourcedefinitions:type=spec
	ServiceAccountCredentialsSecretName string `json:"serviceAccountCredentialsSecretName,omitempty"`

	// The audience of the service account's token used for workload identity authentication requests.
	// +operator-sdk:csv:customresourcedefinitions:type=spec
	ServiceAccountTokenAudience string `json:"serviceAccountTokenAudience,omitempty"`
}

// TelemetryConfigStatus defines the observed state of TelemetryConfig
type TelemetryConfigStatus struct {
	// INSERT ADDITIONAL STATUS FIELD - define observed state of cluster
	// Important: Run "make" to regenerate code after modifying this file

	// For further information see: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties
	// Conditions store the status conditions of the Openshift instances
	// +operator-sdk:csv:customresourcedefinitions:type=status
	Conditions []metav1.Condition `json:"conditions,omitempty" patchStrategy:"merge" patchMergeKey:"type" protobuf:"bytes,1,rep,name=conditions"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status

// TelemetryConfig is the Schema for the telemetryconfigs API
type TelemetryConfig struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   TelemetryConfigSpec   `json:"spec,omitempty"`
	Status TelemetryConfigStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TelemetryConfigList contains a list of TelemetryConfig
type TelemetryConfigList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TelemetryConfig `json:"items"`
}

func init() {
	SchemeBuilder.Register(&TelemetryConfig{}, &TelemetryConfigList{})
}
