//
//Copyright 2024 Google LLC
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//https://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.23.4
// source: protos/collectiondefinition/collectiondefinition.proto

package configuration

import (
	configurablemetrics "github.com/GoogleCloudPlatform/workloadagentplatform/sharedprotos/configurablemetrics"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CollectionDefinition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkloadManager *WorkloadManager `protobuf:"bytes,1,opt,name=workload_manager,json=workloadManager,proto3" json:"workload_manager,omitempty"`
}

func (x *CollectionDefinition) Reset() {
	*x = CollectionDefinition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_collectiondefinition_collectiondefinition_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectionDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionDefinition) ProtoMessage() {}

func (x *CollectionDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_protos_collectiondefinition_collectiondefinition_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionDefinition.ProtoReflect.Descriptor instead.
func (*CollectionDefinition) Descriptor() ([]byte, []int) {
	return file_protos_collectiondefinition_collectiondefinition_proto_rawDescGZIP(), []int{0}
}

func (x *CollectionDefinition) GetWorkloadManager() *WorkloadManager {
	if x != nil {
		return x.WorkloadManager
	}
	return nil
}

type WorkloadManager struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Track the version of the workload manager metrics config distributed for
	// the Workload Agent. This field is intended for debugging purposes only.
	Version      int64         `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	MysqlMetrics *MySQLMetrics `protobuf:"bytes,2,opt,name=mysql_metrics,json=mysqlMetrics,proto3" json:"mysql_metrics,omitempty"`
	RedisMetrics *RedisMetrics `protobuf:"bytes,3,opt,name=redis_metrics,json=redisMetrics,proto3" json:"redis_metrics,omitempty"`
}

func (x *WorkloadManager) Reset() {
	*x = WorkloadManager{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_collectiondefinition_collectiondefinition_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkloadManager) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadManager) ProtoMessage() {}

func (x *WorkloadManager) ProtoReflect() protoreflect.Message {
	mi := &file_protos_collectiondefinition_collectiondefinition_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadManager.ProtoReflect.Descriptor instead.
func (*WorkloadManager) Descriptor() ([]byte, []int) {
	return file_protos_collectiondefinition_collectiondefinition_proto_rawDescGZIP(), []int{1}
}

func (x *WorkloadManager) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *WorkloadManager) GetMysqlMetrics() *MySQLMetrics {
	if x != nil {
		return x.MysqlMetrics
	}
	return nil
}

func (x *WorkloadManager) GetRedisMetrics() *RedisMetrics {
	if x != nil {
		return x.RedisMetrics
	}
	return nil
}

type MySQLMetrics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OsCommandMetrics []*configurablemetrics.OSCommandMetric `protobuf:"bytes,1,rep,name=os_command_metrics,json=osCommandMetrics,proto3" json:"os_command_metrics,omitempty"`
}

func (x *MySQLMetrics) Reset() {
	*x = MySQLMetrics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_collectiondefinition_collectiondefinition_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MySQLMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MySQLMetrics) ProtoMessage() {}

func (x *MySQLMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_protos_collectiondefinition_collectiondefinition_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MySQLMetrics.ProtoReflect.Descriptor instead.
func (*MySQLMetrics) Descriptor() ([]byte, []int) {
	return file_protos_collectiondefinition_collectiondefinition_proto_rawDescGZIP(), []int{2}
}

func (x *MySQLMetrics) GetOsCommandMetrics() []*configurablemetrics.OSCommandMetric {
	if x != nil {
		return x.OsCommandMetrics
	}
	return nil
}

type RedisMetrics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OsCommandMetrics []*configurablemetrics.OSCommandMetric `protobuf:"bytes,1,rep,name=os_command_metrics,json=osCommandMetrics,proto3" json:"os_command_metrics,omitempty"`
}

func (x *RedisMetrics) Reset() {
	*x = RedisMetrics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_collectiondefinition_collectiondefinition_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RedisMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedisMetrics) ProtoMessage() {}

func (x *RedisMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_protos_collectiondefinition_collectiondefinition_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedisMetrics.ProtoReflect.Descriptor instead.
func (*RedisMetrics) Descriptor() ([]byte, []int) {
	return file_protos_collectiondefinition_collectiondefinition_proto_rawDescGZIP(), []int{3}
}

func (x *RedisMetrics) GetOsCommandMetrics() []*configurablemetrics.OSCommandMetric {
	if x != nil {
		return x.OsCommandMetrics
	}
	return nil
}

var File_protos_collectiondefinition_collectiondefinition_proto protoreflect.FileDescriptor

var file_protos_collectiondefinition_collectiondefinition_proto_rawDesc = []byte{
	0x0a, 0x36, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x63, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x29, 0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f,
	0x61, 0x64, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x63,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x1a, 0x50, 0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x64, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x61, 0x62, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x75, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7d, 0x0a, 0x14, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x65, 0x0a,
	0x10, 0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3a, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f,
	0x61, 0x64, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x63,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x52, 0x0f, 0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x22, 0xe7, 0x01, 0x0a, 0x0f, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61,
	0x64, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x5c, 0x0a, 0x0d, 0x6d, 0x79, 0x73, 0x71, 0x6c, 0x5f, 0x6d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x77, 0x6f, 0x72, 0x6b,
	0x6c, 0x6f, 0x61, 0x64, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x64, 0x65, 0x66, 0x69, 0x6e,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4d, 0x79, 0x53, 0x51, 0x4c, 0x4d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x73, 0x52, 0x0c, 0x6d, 0x79, 0x73, 0x71, 0x6c, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73,
	0x12, 0x5c, 0x0a, 0x0d, 0x72, 0x65, 0x64, 0x69, 0x73, 0x5f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f,
	0x61, 0x64, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x63,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x64, 0x69, 0x73, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73,
	0x52, 0x0c, 0x72, 0x65, 0x64, 0x69, 0x73, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x22, 0x85,
	0x01, 0x0a, 0x0c, 0x4d, 0x79, 0x53, 0x51, 0x4c, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x12,
	0x75, 0x0a, 0x12, 0x6f, 0x73, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x5f, 0x6d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x47, 0x2e, 0x77, 0x6f,
	0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x70, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x6d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x73, 0x2e, 0x4f, 0x53, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x4d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x52, 0x10, 0x6f, 0x73, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x4d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x22, 0x85, 0x01, 0x0a, 0x0c, 0x52, 0x65, 0x64, 0x69, 0x73,
	0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x12, 0x75, 0x0a, 0x12, 0x6f, 0x73, 0x5f, 0x63, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x5f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x47, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x73, 0x68, 0x61, 0x72,
	0x65, 0x64, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75,
	0x72, 0x61, 0x62, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x4f, 0x53, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x52, 0x10, 0x6f, 0x73,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x42, 0x43,
	0x5a, 0x41, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x47, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_collectiondefinition_collectiondefinition_proto_rawDescOnce sync.Once
	file_protos_collectiondefinition_collectiondefinition_proto_rawDescData = file_protos_collectiondefinition_collectiondefinition_proto_rawDesc
)

func file_protos_collectiondefinition_collectiondefinition_proto_rawDescGZIP() []byte {
	file_protos_collectiondefinition_collectiondefinition_proto_rawDescOnce.Do(func() {
		file_protos_collectiondefinition_collectiondefinition_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_collectiondefinition_collectiondefinition_proto_rawDescData)
	})
	return file_protos_collectiondefinition_collectiondefinition_proto_rawDescData
}

var file_protos_collectiondefinition_collectiondefinition_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_collectiondefinition_collectiondefinition_proto_goTypes = []interface{}{
	(*CollectionDefinition)(nil),                // 0: workloadagent.protos.collectiondefinition.CollectionDefinition
	(*WorkloadManager)(nil),                     // 1: workloadagent.protos.collectiondefinition.WorkloadManager
	(*MySQLMetrics)(nil),                        // 2: workloadagent.protos.collectiondefinition.MySQLMetrics
	(*RedisMetrics)(nil),                        // 3: workloadagent.protos.collectiondefinition.RedisMetrics
	(*configurablemetrics.OSCommandMetric)(nil), // 4: workloadagentplatform.sharedprotos.configurablemetrics.OSCommandMetric
}
var file_protos_collectiondefinition_collectiondefinition_proto_depIdxs = []int32{
	1, // 0: workloadagent.protos.collectiondefinition.CollectionDefinition.workload_manager:type_name -> workloadagent.protos.collectiondefinition.WorkloadManager
	2, // 1: workloadagent.protos.collectiondefinition.WorkloadManager.mysql_metrics:type_name -> workloadagent.protos.collectiondefinition.MySQLMetrics
	3, // 2: workloadagent.protos.collectiondefinition.WorkloadManager.redis_metrics:type_name -> workloadagent.protos.collectiondefinition.RedisMetrics
	4, // 3: workloadagent.protos.collectiondefinition.MySQLMetrics.os_command_metrics:type_name -> workloadagentplatform.sharedprotos.configurablemetrics.OSCommandMetric
	4, // 4: workloadagent.protos.collectiondefinition.RedisMetrics.os_command_metrics:type_name -> workloadagentplatform.sharedprotos.configurablemetrics.OSCommandMetric
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_protos_collectiondefinition_collectiondefinition_proto_init() }
func file_protos_collectiondefinition_collectiondefinition_proto_init() {
	if File_protos_collectiondefinition_collectiondefinition_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_collectiondefinition_collectiondefinition_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectionDefinition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_collectiondefinition_collectiondefinition_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkloadManager); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_collectiondefinition_collectiondefinition_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MySQLMetrics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_collectiondefinition_collectiondefinition_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RedisMetrics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_collectiondefinition_collectiondefinition_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_collectiondefinition_collectiondefinition_proto_goTypes,
		DependencyIndexes: file_protos_collectiondefinition_collectiondefinition_proto_depIdxs,
		MessageInfos:      file_protos_collectiondefinition_collectiondefinition_proto_msgTypes,
	}.Build()
	File_protos_collectiondefinition_collectiondefinition_proto = out.File
	file_protos_collectiondefinition_collectiondefinition_proto_rawDesc = nil
	file_protos_collectiondefinition_collectiondefinition_proto_goTypes = nil
	file_protos_collectiondefinition_collectiondefinition_proto_depIdxs = nil
}
